version: '3'

services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: 123
  
  adminer:
    image: adminer
    environment:
      ADMINER_DEFAULT_SERVER: db
      ADMINER_DESIGN: dracula
    ports:
      - 8080:8080
    depends_on:
      - db

  www:
    build:
      ./php
    volumes:
      - ./app:/var/www/html
    ports:
      - 80:80
    depends_on:
      - db

  node:
    image: "node:19"
    working_dir: /var/www/html
    volumes:
      - ./app:/var/www/html
    ports:
      - 5173:5173
  